export { AccountsPage as AccountsScreen } from '@/pages/system-pages'
export { DevicesPage as DevicesScreen } from '@/pages/system-pages'
export { ReportsPage as ReportsScreen } from '@/pages/system-pages'
export { OptionsPage as OptionsScreen } from '@/pages/system-pages'
export { LogsPage as LogsScreen } from '@/pages/logs-page'
export { AboutPage as AboutScreen } from '@/pages/system-pages'
